export enum UserPermission {
    VIEW_ANY_BUSINESS = 'Lihat Data Bisnis Keseluruhan',
    VIEW_OWN_BUSINESS = 'Lihat Data Bisnis Pribadi',
    CREATE_ANY_BUSINESS = 'Tambah Data Bisnis Keseluruhan',
    CREATE_OWN_BUSINESS = 'Tambah Data Bisnis Pribadi',
    EDIT_ANY_BUSINESS = 'Edit Data Bisnis Keseluruhan',
    EDIT_OWN_BUSINESS = 'Edit Data Bisnis Pribadi',
    DELETE_ANY_BUSINESS = 'Hapus Data Bisnis Keseluruhan',
    DELETE_OWN_BUSINESS = 'Hapus Data Bisnis Pribadi',

    VIEW_ANY_BRANCH = 'Lihat Data Cabang Keseluruhan',
    VIEW_ASSOCIATED_BRANCH = 'Lihat Data Cabang Penanggungjawab Bisnis',
    VIEW_OWN_BRANCH = 'Lihat Data Cabang Pribadi',
    CREATE_ANY_BRANCH = 'Tambah Data Cabang Keseluruhan',
    CREATE_ASSOCIATED_BRANCH = 'Tambah Data Cabang Penanggungjawab Bisnis',
    CREATE_OWN_BRANCH = 'Tambah Data Cabang Pribadi',
    EDIT_ANY_BRANCH = 'Edit Data Cabang Keseluruhan',
    EDIT_ASSOCIATED_BRANCH = 'Edit Data Cabang Penanggungjawab Bisnis',
    EDIT_OWN_BRANCH = 'Edit Data Cabang Pribadi',
    DELETE_ANY_BRANCH = 'Hapus Data Cabang Keseluruhan',
    DELETE_ASSOCIATED_BRANCH = 'Hapus Data Cabang Penanggungjawab Bisnis',
    DELETE_OWN_BRANCH = 'Hapus Data Cabang Pribadi',

    VIEW_ANY_PRODUCT = 'Lihat Data Produk Keseluruhan',
    VIEW_ASSOCIATED_PRODUCT = 'Lihat Data Produk Penempatan Bisnis',
    VIEW_OWN_PRODUCT = 'Lihat Data Produk Pribadi',
    CREATE_ANY_PRODUCT = 'Tambah Data Produk Keseluruhan',
    CREATE_ASSOCIATED_PRODUCT = 'Tambah Data Produk Penempatan Bisnis',
    CREATE_OWN_PRODUCT = 'Tambah Data Produk Pribadi',
    EDIT_ANY_PRODUCT = 'Edit Data Produk Keseluruhan',
    EDIT_ASSOCIATED_PRODUCT = 'Edit Data Produk Penempatan Bisnis',
    EDIT_OWN_PRODUCT = 'Edit Data Produk Pribadi',
    DELETE_ANY_PRODUCT = 'Hapus Data Produk Keseluruhan',
    DELETE_ASSOCIATED_PRODUCT = 'Hapus Data Produk Penempatan Bisnis',
    DELETE_OWN_PRODUCT = 'Hapus Data Produk Pribadi',

    VIEW_ANY_SUPPLIER = 'Lihat Data Supplier Keseluruhan',
    VIEW_ASSOCIATED_SUPPLIER = 'Lihat Data Supplier Penempatan Bisnis',
    VIEW_OWN_SUPPLIER = 'Lihat Data Supplier Pribadi',
    CREATE_ANY_SUPPLIER = 'Tambah Data Supplier Keseluruhan',
    CREATE_ASSOCIATED_SUPPLIER = 'Tambah Data Supplier Penempatan Bisnis',
    CREATE_OWN_SUPPLIER = 'Tambah Data Supplier Pribadi',
    EDIT_ANY_SUPPLIER = 'Edit Data Supplier Keseluruhan',
    EDIT_ASSOCIATED_SUPPLIER = 'Edit Data Supplier Penempatan Bisnis',
    EDIT_OWN_SUPPLIER = 'Edit Data Supplier Pribadi',
    DELETE_ANY_SUPPLIER = 'Hapus Data Supplier Keseluruhan',
    DELETE_ASSOCIATED_SUPPLIER = 'Hapus Data Supplier Penempatan Bisnis',
    DELETE_OWN_SUPPLIER = 'Hapus Data Supplier Pribadi',

    VIEW_ROLE = 'Lihat Data Role Permisison',
    CREATE_ROLE = 'Tambah Data Role Permisison',
    EDIT_ROLE = 'Edit Data Role Permisison',
    DELETE_ROLE = 'Hapus Data Role Permission',

    VIEW_ANY_CUSTOMER = 'Lihat Data Customer Keseluruhan',
    VIEW_ASSOCIATED_CUSTOMER = 'Lihat Data Customer Penempatan Bisnis',
    VIEW_OWN_CUSTOMER = 'Lihat Data Customer Pribadi',
    CREATE_ANY_CUSTOMER = 'Tambah Data Customer Keseluruhan',
    CREATE_ASSOCIATED_CUSTOMER = 'Tambah Data Customer Penempatan Bisnis',
    CREATE_OWN_CUSTOMER = 'Tambah Data Customer Pribadi',
    EDIT_ANY_CUSTOMER = 'Edit Data Customer Keseluruhan',
    EDIT_ASSOCIATED_CUSTOMER = 'Edit Data Customer Penempatan Bisnis',
    EDIT_OWN_CUSTOMER = 'Edit Data Customer Pribadi',
    DELETE_ANY_CUSTOMER = 'Hapus Data Customer Keseluruhan',
    DELETE_ASSOCIATED_CUSTOMER = 'Hapus Data Customer Penempatan Bisnis',
    DELETE_OWN_CUSTOMER = 'Hapus Data Customer Pribadi',

    VIEW_ANY_PRODUCT_UNIT = 'Lihat Data Satuan Produk Keseluruhan',
    VIEW_ASSOCIATED_PRODUCT_UNIT = 'Lihat Data Satuan Produk Penempatan Bisnis',
    VIEW_OWN_PRODUCT_UNIT = 'Lihat Data Satuan Produk Pribadi',
    CREATE_ANY_PRODUCT_UNIT = 'Tambah Data Satuan Produk Keseluruhan',
    CREATE_ASSOCIATED_PRODUCT_UNIT = 'Tambah Data Satuan Produk Penempatan Bisnis',
    CREATE_OWN_PRODUCT_UNIT = 'Tambah Data Satuan Produk Pribadi',
    EDIT_ANY_PRODUCT_UNIT = 'Edit Data Satuan Produk Keseluruhan',
    EDIT_ASSOCIATED_PRODUCT_UNIT = 'Edit Data Satuan Produk Penempatan Bisnis',
    EDIT_OWN_PRODUCT_UNIT = 'Edit Data Satuan Produk Pribadi',
    DELETE_ANY_PRODUCT_UNIT = 'Hapus Data Satuan Produk Keseluruhan',
    DELETE_ASSOCIATED_PRODUCT_UNIT = 'Hapus Data Satuan Produk Penempatan Bisnis',
    DELETE_OWN_PRODUCT_UNIT = 'Hapus Data Satuan Produk Pribadi',

    VIEW_ANY_REWARD = 'Lihat Data Reward Keseluruhan',
    VIEW_ASSOCIATED_REWARD = 'Lihat Data Reward Penempatan Bisnis',
    VIEW_OWN_REWARD = 'Lihat Data Reward Pribadi',
    CREATE_ANY_REWARD = 'Tambah Data Reward Keseluruhan',
    CREATE_ASSOCIATED_REWARD = 'Tambah Data Reward Penempatan Bisnis',
    CREATE_OWN_REWARD = 'Tambah Data Reward Pribadi',
    EDIT_ANY_REWARD = 'Edit Data Reward Keseluruhan',
    EDIT_ASSOCIATED_REWARD = 'Edit Data Reward Penempatan Bisnis',
    EDIT_OWN_REWARD = 'Edit Data Reward Pribadi',
    DELETE_ANY_REWARD = 'Hapus Data Reward Keseluruhan',
    DELETE_ASSOCIATED_REWARD = 'Hapus Data Reward Penempatan Bisnis',
    DELETE_OWN_REWARD = 'Hapus Data Reward Pribadi',

    VIEW_ANY_PRODUCT_ITEM = 'Lihat Data Item Produk Keseluruhan',
    VIEW_ASSOCIATED_PRODUCT_ITEM = 'Lihat Data Item Produk Penempatan Bisnis',
    VIEW_OWN_PRODUCT_ITEM = 'Lihat Data Item Produk Pribadi',
    CREATE_ANY_PRODUCT_ITEM = 'Tambah Data Item Produk Keseluruhan',
    CREATE_ASSOCIATED_PRODUCT_ITEM = 'Tambah Data Item Produk Penempatan Bisnis',
    CREATE_OWN_PRODUCT_ITEM = 'Tambah Data Item Produk Pribadi',
    EDIT_ANY_PRODUCT_ITEM = 'Edit Data Item Produk Keseluruhan',
    EDIT_ASSOCIATED_PRODUCT_ITEM = 'Edit Data Item Produk Penempatan Bisnis',
    EDIT_OWN_PRODUCT_ITEM = 'Edit Data Item Produk Pribadi',
    DELETE_ANY_PRODUCT_ITEM = 'Hapus Data Item Produk Keseluruhan',
    DELETE_ASSOCIATED_PRODUCT_ITEM = 'Hapus Data Item Produk Penempatan Bisnis',
    DELETE_OWN_PRODUCT_ITEM = 'Hapus Data Item Produk Pribadi',

    VIEW_ANY_PURCHASE_RECEIPT = 'Lihat Data Penerimaan Barang Keseluruhan',
    VIEW_OWN_PURCHASE_RECEIPT = 'Lihat Data Penerimaan Barang Pribadi',
    VIEW_ASSOCIATED_PURCHASE_RECEIPT = 'Lihat Data Penerimaan Barang Penempatan Bisnis',
    VIEW_ANY_STOCK_ADJUSTMENT = 'Lihat Data Stock Opname Keseluruhan',
    VIEW_OWN_STOCK_ADJUSTMENT = 'Lihat Data Stock Opname Pribadi',
    VIEW_ASSOCIATED_STOCK_ADJUSTMENT = 'Lihat Data Stock Opname Penempatan Bisnis',

    VIEW_USER = 'Lihat Data User',
    CREATE_USER = 'Tambah Data User',
    EDIT_USER = 'Edit Data User',
    DELETE_USER = 'Hapus Data User',
    CASHIER = 'Manajemen Kasir',
    VIEW_ANY_TRANSACTION = 'Lihat Data Transaksi Keseluruhan',
    VIEW_OWN_TRANSACTION = 'Lihat Data Transaksi Pribadi',
    VIEW_ASSOCIATED_TRANSACTION = 'Lihat Data Transaksi Penempatan Bisnis',
    VIEW_ANY_PRODUCT_TRANSACTION = 'Lihat Data Transaksi Produk Keseluruhan',
    VIEW_OWN_PRODUCT_TRANSACTION = 'Lihat Data Transaksi Produk Pribadi',
    VIEW_ASSOCIATED_PRODUCT_TRANSACTION = 'Lihat Data Transaksi Produk Penempatan Bisnis'
}
